# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_tutorial_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_area',
            name='slug',
            field=models.SlugField(default='', max_length=40, unique=True),
        ),
    ]
