# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_practice_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile'),
        ),
    ]
