# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-22 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_practice_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice_question',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=110, unique=True),
        ),
    ]
