# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-22 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180822_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice_area',
            old_name='slug',
            new_name='area_slug',
        ),
        migrations.RenameField(
            model_name='practice_question',
            old_name='slug',
            new_name='question_slug',
        ),
    ]
