# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 20:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180502_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_id',
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=ckeditor.fields.RichTextField(default='', max_length=750, verbose_name='iş tanımı'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_name',
            field=models.TextField(default='', max_length=100, verbose_name='iş ismi'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='', max_length=250, verbose_name='firma ismi'),
        ),
    ]
