# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-27 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180823_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice_question',
            name='level',
            field=models.CharField(choices=[('kolay', 'KOLAY'), ('orta', 'ORTA'), ('zor', 'ZOR'), ('çok zor', 'ÇOK ZOR')], default='kolay', max_length=10),
        ),
        migrations.AddField(
            model_name='practice_question',
            name='point',
            field=models.FloatField(default=0),
        ),
    ]
