# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-27 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180927_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice_question',
            name='level',
            field=models.CharField(choices=[('Kolay', 'KOLAY'), ('Orta', 'ORTA'), ('Zor', 'ZOR'), ('Çok zor', 'ÇOK ZOR')], default='kolay', max_length=10),
        ),
    ]
